name: PRODDeploy

env:
  PHP_VERSION: '8.x'
  CI: false

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: hindurunner
    steps:
      - name: Setup PHP
        uses: actions/checkout@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Additional steps for caching and installing dependencies (unchanged)

      - name: Zip artifact for deployment
        run: Compress-Archive -Path .\* -DestinationPath release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php_app
          path: release.zip

  deploy:
    runs-on: hindurunner
    needs: build
    environment:
      name: 'hindu1'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: php_app
          path: C:\Users\runnervm\actions-runner1\_work

      - name: Install sshpass
        uses: appleboy/ssh-action@master
        with:
          target: linux
          host: ${{ secrets.NEW_VM_PRIVATE_IP }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22

      - name: Deploy to New VM with Password
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -r C:\Users\runnervm\actions-runner1\_work\php_app\* ${{ secrets.VM_USERNAME }}@${{ secrets.NEW_VM_PRIVATE_IP }}:/home/hindu-prod1/prod
