name: PRODDeploy

env:
  PHP_VERSION: '8.x'
  CI: false

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: hindurunner
    steps:
      - name: Setup PHP
        uses: actions/checkout@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Additional steps for caching and installing dependencies (unchanged)

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php_app
          path: release.zip

  deploy:
    runs-on: hindurunner
    needs: build
    environment:
      name: 'hindu1'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: php_app
          path: C:\Users\runnervm\actions-runner1\_work

      - name: Copy artifacts to azure VM
        uses: azure/scp-action@v2
        with:
          host: '10.0.2.6'
          username: 'azureuser'
          password: 'Sumanth@4-54'
          source: C:\Users\runnervm\actions-runner1\_work
          target: '/home/hindu-prod1/prod'
