name: PRODDeploy

env:
  PHP_VERSION: '8.x'
  CI: false

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: hindurunner
    steps:
      - name: Setup PHP
        uses: actions/checkout@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Additional steps for caching and installing dependencies (unchanged)

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php_app
          path: release.zip

  deploy:
    runs-on: hindurunner
    needs: build
    environment:
      name: 'hindu1'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: php_app
          path: C:\Users\runnervm\actions-runner1\_work

      - name: Deploy to VM with Password
        uses: plileggi/remote-ssh-action@v2
        with:
          host: ${{ secrets.VM_PRIVATE_IP }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            # Navigate to the folder where the artifact is downloaded
            cd /home/hindu-prod1/prod

            # Copy the artifact to the remote VM
            scp -P ${{ secrets.VM_SSH_PORT }} /Users/runnervm/actions-runner1/_work/release.zip ${{ secrets.VM_USERNAME }}@${{ secrets.VM_PRIVATE_IP }}:/home/hindu-prod1/prod

            # Connect to the remote VM and perform deployment tasks
            ssh -p ${{ secrets.VM_SSH_PORT }} ${{ secrets.VM_USERNAME }}@${{ secrets.VM_PRIVATE_IP }} "cd /home/hindu-prod1/prod && unzip release.zip && ./deploy.sh"
