name: PRODDeploy

env:
  PHP_VERSION: '8.x'
  CI: false

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: hindurunner
    steps:
      - name: Setup PHP
        uses: actions/checkout@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Additional steps for caching and installing dependencies (unchanged)

      - name: Zip artifact for deployment
        run: Compress-Archive -Path .\* -DestinationPath release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php_app
          path: release.zip

  deploy:
    runs-on: hindurunner
    needs: build
    environment:
      name: 'hindu1'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: php_app
          path: C:\Users\runnervm\actions-runner1\_work

      - name: Deploy to New VM with Password
        run: |
          $securePassword = ConvertTo-SecureString -String "${{ secrets.VM_PASSWORD }}" -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential -ArgumentList ("${{ secrets.VM_USERNAME }}", $securePassword)
          Copy-Item -Path C:\Users\runnervm\actions-runner1\_work\php_app\* -Destination "\\${{ secrets.NEW_VM_PRIVATE_IP }}\C$\home\hindu-prod1\prod" -Credential $credentials
